 apiVersion: kustomize.config.k8s.io/v1beta1
 kind: Kustomization

 namespace: argocd

 resources:
   - argocd-demo.yaml
   - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
   - podinfo-demo-argo.yaml
